name: Tests (Legacy CUDA)

on: [push, pull_request]

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo check --tests

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false
      - uses: arduino/setup-protoc@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.5.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test -p kaspa-miner
      - run: cargo test -p kaspa-miner --features=no-asm
      - run: cargo test -p kaspa-miner --no-default-features
      - run: cargo test -p kaspa-miner --no-default-features --features=shuttle
      - run: cargo test -p kaspaopencl

  test-release:
    name: Test Suite Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false
      - uses: arduino/setup-protoc@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.5.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --release -p kaspa-miner
      - run: cargo test --features=no-asm --release -p kaspa-miner
      - run: cargo test --no-default-features --release -p kaspa-miner
      - run: cargo test --no-default-features --features=shuttle --release -p kaspa-miner
      - run: cargo test --release -p kaspaopencl

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --tests -- -D warnings
